apiVersion: v1
kind: Secret
metadata:
  name: secret-banco-noticias
type: Opaque
data:
  # Os valores em Secrets são codificados em Base64
  MYSQL_ROOT_PASSWORD: cTF3MmUzcjQ= # q1w2e3r4
  MYSQL_PASSWORD: cTF3MmUzcjQ=      # q1w2e3r4