apiVersion: v1                    
kind: Service                        
metadata:                         
  name: svc-pod-banco-noticias
spec:                            
  type: NodePort
  ports:
    - port: 3306
      #protocol: TCP
      #targetPort: 80
      nodePort: 30002
  selector:
    app: pod-banco-noticias